### ISSUE TITLE
The template can only be deployed on us-east-1 region

### ISSUE THREAD

**Issue by namelivia** [buzzsurfr/athena-add-partition#2]
I've tried deploying the template on eu-west-1 but I can't because the create lambda function step fails with an error stating that the bucket is in us-east-1 region. I think it is because of the bucket that stores the lambda function zip file.
I'm not sure the template is intended to be region-independent (is it easy or even feasable?) or should it be managed by making another version.

**Comment by buzzsurfr** [comment]
This is a simple change. I'm moving the codebase to regionalized S3 buckets for hosting and will update the links on the README.

**Comment by buzzsurfr** [comment]
@namelivia Fixed, check the README for regionalized links. I didn't verify all regions, but I did verify `eu-west-1`.

Thanks for contributing!
