### ISSUE TITLE
https://s3.amazonaws.com/athena-add-partition-us-east-1/template.json  forbidden

### ISSUE THREAD

**Issue by carcuevas** [buzzsurfr/athena-add-partition#3]
Hello, 

I wanted to give a try to your Cloudformation scripts with the lambdas and so, but somehow I cannot access to the S3, should I use the template.json from this repository?

Thanks very much for your work and time :)

**Comment by buzzsurfr** [comment]
Use the template.json in the repo—I will check permissions on the S3 bucket and fix as well.

**Comment by carcuevas** [comment]
Ohh thanks very much again :)

**Comment by buzzsurfr** [comment]
@carcuevas There was an issue with the bucket permissions. I've fixed the permissions on the backend.

Thanks for letting me know!
